[application]
name = "groundstation_frontend"
default_platform = "web"
out_dir = "dist"
# This folder is copied into the output dir after build/serve
asset_dir = "web"
icon = "web/favicon.png"

# If this is a workspace, uncomment and set:
# sub_package = "groundstation_frontend"

[web.app]
title = "GroundStation 26"

[web.watcher]
watch_path = ["src", "web"]
reload_html = true
index_on_404 = true

# If wasm-opt keeps crashing on your machine, disable it
# (In 0.7, wasm-opt is configured under [web.wasm_opt])
[web.wasm_opt]
level = "3"
debug = false

[bundle.macos]
info_plist_path = "platform/macos/Info.plist"

[bundle.ios]
info_plist_path = "platform/ios/Info.plist"