[application]
name = "GroundStation 26"
default_platform = "web"
out_dir = "dist"
# This folder is copied into the output dir after build/serve
asset_dir = "assets"
icon = "assets/icon.png"
category = "public.app-category.utilities"
version = "0.1.2"

[web.app]
title = "GroundStation 26"

[web.watcher]
watch_path = ["src", "assets"]
reload_html = true
index_on_404 = true

[web.wasm_opt]
level = "3"
debug = false

[bundle]
name = "GroundStation 26"
identifier = "com.UBSEDS.GS26"
publisher = "UBSEDS"
icon = ["assets/icon.png"]

[bundle.macos]
# Used for BOTH macOS and iOS bundles
info_plist_path = "platform/macos/Info.plist"
minimum_system_version = "13.0"
hardened_runtime = true


[bundle.ios]
icon = "assets/icon.png"