services:
  web:
    build:
      context: .
      args:
        # Default value; build.py/docker path will override this when needed
        PI_BUILD: ""
    networks:
      - internal
    environment:
      ENSURE_MAP_DATA: "true"
    volumes:
      - ./data:/app/data
      - ./backend/data:/app/backend/data
    restart: always
