services:
  web:
    build:
      context: .
      args:
        # Default value; build.py/docker path will override this when needed
        PI_BUILD: ""
        TESTING: ""
    networks:
      - internal
    environment:
      ENSURE_MAP_DATA: "true"
    volumes:
      - ./data:/app/data
      - ./backend/data:/app/backend/data
    restart: always
    # Uncomment the following lines to allow GPIO access from the container. This is needed for testing on Raspberry Pi
    # devices, but should be left disabled for development on other platforms.
#    devices:
#      - /dev/gpiochip0:/dev/gpiochip0
#      - /dev/gpiochip1:/dev/gpiochip1
#      - /dev/gpiochip2:/dev/gpiochip2
#      - /dev/gpiochip3:/dev/gpiochip3
#      - /dev/gpiochip4:/dev/gpiochip4
#      - /dev/gpiomem0:/dev/gpiomem0
#      - /dev/gpiomem1:/dev/gpiomem1
#      - /dev/gpiomem2:/dev/gpiomem2
#      - /dev/gpiomem3:/dev/gpiomem3
#      - /dev/gpiomem4:/dev/gpiomem4

  nginx:
    build: ./nginx
    ports:
      - "3000:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_certs:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - internal
      - external
    restart: always


networks:
  internal:
    internal: true
  external:
    driver: bridge