# .cargo/config.toml
[env]
DEVICE_IDENTIFIER = "GS"
IPHONEOS_DEPLOYMENT_TARGET = "13.0"
CARGO_TARGET_AARCH64_APPLE_IOS_DEPLOYMENT_TARGET = "13.0"
CARGO_TARGET_AARCH64_APPLE_IOS_SIM_DEPLOYMENT_TARGET = "13.0"
